version: '3.8'
services:
  feralcat-db:
    image: postgres:15.1-alpine
    container_name: feralcat-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${FERALCAT_DB_USER}"
      POSTGRES_PASSWORD: "${FERALCAT_DB_USER_PASSWORD}"
      POSTGRES_MULTIPLE_DATABASES: feralcat_keycloak_db,feralcat_accounts_db
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d

  feralcat-cache:
    image: redis:7.0.5-alpine
    container_name: feralcat-cache
    ports:
      - "6379:6379"

  feralcat-zookeeper:
    image: bitnami/zookeeper:3.8.0
    container_name: feralcat-zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  feralcat-kafka:
    image: bitnami/kafka:3.3.1
    container_name: feralcat-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: feralcat-zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - feralcat-zookeeper

  feralcat-keycloak:
    image: bitnami/keycloak:19.0.3
    container_name: feralcat-keycloak
    ports:
      - "8090:8080"
    environment:
      KEYCLOAK_ADMIN_USER: keycloak_admin
      KEYCLOAK_ADMIN_PASSWORD: "${FERALCAT_KEYCLOAK_ADMIN_PASSWORD}"
      KEYCLOAK_MANAGEMENT_USER: keycloak_manager
      KEYCLOAK_MANAGEMENT_PASSWORD: "${FERALCAT_KEYCLOAK_MANAGER_PASSWORD}"
      KEYCLOAK_DATABASE_HOST: feralcat-db
      KEYCLOAK_DATABASE_NAME: feralcat_keycloak_db
      KEYCLOAK_DATABASE_USER: "${FERALCAT_DB_USER}"
      KEYCLOAK_DATABASE_PASSWORD: "${FERALCAT_DB_USER_PASSWORD}"
    depends_on:
      - feralcat-db
